


version: 2
jobs:
    hello:
        steps:
          - checkout
          - run:
            name : Greet
            command: echo "Hello World"
    build:
        docker:
            - image: circleci/node:7
        steps:
            - checkout
            - run:
                name: tests
                command: npm test
          
 workflows:
   version: 2
   hello_and_build:
     jobs:
       - one
       - two