
 version: 2
 jobs:
   build:
     docker:
       - image: circleci/node:12.14
     steps:
       - checkout
       - run: echo "First Hello World"
    build:
     docker:
       - image: circleci/node:12.14
     steps:
       - checkout
       - run: echo "Second Hello World"