
version: 2
jobs:
   build:
     docker:
       - image: circleci/node:12.14
     steps:
       - checkout
       - run: echo "A first Hello World"

   test:
     steps:
       - checkout
       - run: echo "A Second Hello World"

workflows:
   version: 2
   build_and_test:
     jobs:
       - build
       - test:
          requires:
            - build