


 version: 2
 jobs:
   one:
     docker:
       - image: circleci/node:12.14
     steps:
       - checkout
       - run: echo "A first Hello"
   two:
      docker:
       - image: circleci/node:12.14
     steps:
       - checkout
       - run: echo "A second Hello"

 workflows:
   version: 2
   one_and_two:
     jobs:
       - one
       - two