
 version: 2
 jobs:
   build:
     docker:
       - image: circleci/ruby:2.4.1
     steps:
       - checkout
       - run: echo "A first Hello World"
   test:
     docker:
       - image: circleci/ruby:2.4.1
     steps:
       - checkout
       - run: npm test

 workflows:
   version: 2
   build_and_test:
     jobs:
       - build
       - test